const TFR={sb:window.supabase.createClient(window.TFR_SUPABASE_URL,window.TFR_SUPABASE_PUBLISHABLE_KEY),products:[],cart:JSON.parse(localStorage.getItem('tfr_cart')||'[]'),favs:JSON.parse(localStorage.getItem('tfr_favs')||'[]')};
const $=s=>document.querySelector(s);let activeCategory=window.TFR_CATEGORY||'Todos';
function saveCart(){localStorage.setItem('tfr_cart',JSON.stringify(TFR.cart))}function saveFavs(){localStorage.setItem('tfr_favs',JSON.stringify(TFR.favs))}
function stockState(p){const n=Number(p.stock||0);return n<=0?{text:'Agotado',cls:'off'}:n<=2?{text:`Últimas ${n}`,cls:'low'}:{text:'Disponible',cls:'ok'}}
async function loadProducts(){const r=await TFR.sb.from('products').select('id,name,category,price,stock,unit,image,description,featured').eq('active',true).order('featured',{ascending:false}).order('name',{ascending:true});if(!r.error&&Array.isArray(r.data)){TFR.products=r.data;localStorage.setItem('tfr_products_cache',JSON.stringify(r.data));return}try{const c=JSON.parse(localStorage.getItem('tfr_products_cache')||'[]');TFR.products=c.length?c:(window.TFR_FALLBACK_PRODUCTS||[])}catch{TFR.products=window.TFR_FALLBACK_PRODUCTS||[]}}
function updateHeader(){if($('#cartCount'))$('#cartCount').textContent=TFR.cart.reduce((a,x)=>a+Number(x.qty||0),0);if($('#favCount'))$('#favCount').textContent=TFR.favs.length}
function renderFilters(){const n=$('#filters');if(!n)return;const cats=['Todos',...new Set(TFR.products.map(p=>p.category))];n.innerHTML=cats.map(c=>`<button type="button" class="chip ${c===activeCategory?'active':''}" onclick="setCategory(${JSON.stringify(c)})">${c}</button>`).join('')}
function setCategory(c){activeCategory=c;renderFilters();renderProducts()}
function addCart(id){const p=TFR.products.find(x=>x.id===id);if(!p||Number(p.stock)<=0)return;let l=TFR.cart.find(x=>x.id===id);if(l){if(l.qty>=Number(p.stock))return alert('No hay más unidades disponibles.');l.qty++}else TFR.cart.push({id,qty:1});saveCart();updateHeader();openCart()}
function changeQty(id,d){const l=TFR.cart.find(x=>x.id===id),p=TFR.products.find(x=>x.id===id);if(!l||!p)return;l.qty=Math.max(0,Math.min(Number(p.stock),l.qty+d));if(!l.qty)TFR.cart=TFR.cart.filter(x=>x.id!==id);saveCart();updateHeader();openCart()}
function removeCart(id){TFR.cart=TFR.cart.filter(x=>x.id!==id);saveCart();updateHeader();openCart()}
function toggleFav(id){const i=TFR.favs.indexOf(id);i>=0?TFR.favs.splice(i,1):TFR.favs.push(id);saveFavs();updateHeader();renderProducts();renderCategorySections()}
function cartItems(){return TFR.cart.map(x=>({...x,p:TFR.products.find(p=>p.id===x.id)})).filter(x=>x.p)}function cartTotal(){return cartItems().reduce((a,x)=>a+x.p.price*x.qty,0)}
function openCart(){const d=$('#drawer'),c=$('#drawerContent');if(!d||!c)return;d.classList.add('show');const its=cartItems();c.innerHTML=its.length?`<h2>🛒 Tu carrito</h2>${its.map(x=>`<div class="drawer-item"><img src="${x.p.image}" alt="${x.p.name}"><div><b>${x.p.name}</b><div>${Number(x.p.price).toFixed(2)} € / ${x.p.unit||'unidad'}</div><div class="qty-row"><button class="qty" onclick="changeQty('${x.p.id}',-1)">−</button><strong>${x.qty}</strong><button class="qty" onclick="changeQty('${x.p.id}',1)">+</button></div></div><button class="remove-line" onclick="removeCart('${x.p.id}')">✕</button></div>`).join('')}<div class="drawer-summary"><div><span>Productos</span><b>${its.reduce((a,x)=>a+x.qty,0)}</b></div><div><span>Recogida en tienda</span><b>Gratis</b></div><div class="drawer-total"><span>Total</span><b>${cartTotal().toFixed(2).replace('.',',')} €</b></div></div><button class="btn" style="width:100%;margin-top:16px" onclick="location.href='checkout.html'">Continuar al pedido</button>`:'<h2>🛒 Tu carrito</h2><div class="empty">Tu carrito está vacío.</div>'}
function closeDrawer(){$('#drawer')?.classList.remove('show')}
function productCard(p){const s=stockState(p),fav=TFR.favs.includes(p.id);return `<article class="product"><a class="photo" href="producto.html?id=${encodeURIComponent(p.id)}" style="background-image:url('${p.image}')"></a><div class="pbody"><span class="tag">${p.category.toUpperCase()}</span><h3><a href="producto.html?id=${encodeURIComponent(p.id)}">${p.name}</a></h3><p class="desc">${p.description||''}</p><div class="price-row"><span class="price">${Number(p.price).toFixed(2).replace('.',',')} € / ${p.unit||'unidad'}</span><span class="stock ${s.cls}">${s.text}</span></div><div class="pactions"><button class="buy" ${s.cls==='off'?'disabled':''} onclick="addCart('${p.id}')">🛒 Añadir</button><button class="fav ${fav?'on':''}" onclick="toggleFav('${p.id}')">${fav?'♥':'♡'}</button></div><a class="wh" href="https://wa.me/34612412469?text=${encodeURIComponent('Hola The Fish Room, me interesa '+p.name+'. ¿Sigue disponible?')}" target="_blank" rel="noopener">💬 Consultar por WhatsApp</a></div></article>`}
function sortList(a){const s=$('#sort')?.value||'featured';if(s==='priceAsc')a.sort((x,y)=>x.price-y.price);else if(s==='priceDesc')a.sort((x,y)=>y.price-x.price);else if(s==='name')a.sort((x,y)=>x.name.localeCompare(y.name));else a.sort((x,y)=>Number(y.featured)-Number(x.featured)||x.name.localeCompare(y.name));return a}
function renderProducts(){const n=$('#products');if(!n)return;const q=($('#search')?.value||'').toLowerCase().trim();const a=sortList(TFR.products.filter(p=>(activeCategory==='Todos'||p.category===activeCategory)&&(`${p.name} ${p.category} ${p.description||''}`).toLowerCase().includes(q)));n.innerHTML=a.map(productCard).join('')||'<div class="empty">No hay productos con esos filtros.</div>'}
function renderCategorySections(){const n=$('#categorySections');if(!n)return;const cats=['Bettas','Guppys','Cíclidos','Plantas'];n.innerHTML=cats.map(c=>{const a=TFR.products.filter(p=>p.category===c).slice(0,4);return a.length?`<section class="category-section"><div class="section-head"><div><span class="eyebrow">${c.toUpperCase()}</span><h3>${c}</h3></div><a class="btn ghost" href="categoria.html?c=${encodeURIComponent(c)}">Ver categoría</a></div><div class="products">${a.map(productCard).join('')}</div></section>`:''}).join('')}
function renderReviews(){if($('#reviews'))$('#reviews').innerHTML='<article class="review"><div class="stars">★★★★★</div><b>Próximamente</b><p>Las primeras reseñas reales de The Fish Room aparecerán aquí.</p></article>'}
async function submitService(e){e.preventDefault();const p={p_service:$('#service').value,p_request_type:$('#bookingType').value,p_requested_date:$('#date').value,p_requested_time:$('#time').value,p_customer_name:$('#clientName').value.trim(),p_customer_phone:$('#clientPhone').value.trim(),p_address:$('#address').value.trim()||null,p_description:$('#problem').value.trim()||null};const r=await TFR.sb.rpc('create_service_request',p);if(r.error)return alert('No se pudo guardar la solicitud: '+r.error.message);const msg=[`Solicitud de servicio ${r.data?.id||''}`,`Servicio: ${p.p_service}`,`Tipo: ${p.p_request_type}`,`Fecha: ${p.p_requested_date} ${p.p_requested_time}`,`Cliente: ${p.p_customer_name}`,`Teléfono: ${p.p_customer_phone}`,p.p_address?`Dirección: ${p.p_address}`:'',p.p_description?`Descripción: ${p.p_description}`:''].filter(Boolean).join('\n');window.open('https://wa.me/34612412469?text='+encodeURIComponent(msg),'_blank');e.target.reset();alert('Solicitud guardada correctamente.')}
document.addEventListener('DOMContentLoaded',async()=>{await loadProducts();updateHeader();renderFilters();renderProducts();renderCategorySections();renderReviews();$('#cartBtn')?.addEventListener('click',openCart);$('#search')?.addEventListener('input',renderProducts);$('#sort')?.addEventListener('change',renderProducts);$('#bookingForm')?.addEventListener('submit',submitService);$('#drawer')?.addEventListener('click',e=>{if(e.target.id==='drawer')closeDrawer()})});
window.setCategory=setCategory;window.addCart=addCart;window.changeQty=changeQty;window.removeCart=removeCart;window.toggleFav=toggleFav;window.openCart=openCart;window.closeDrawer=closeDrawer;window.productCard=productCard;window.loadProducts=loadProducts;window.stockState=stockState;window.TFR=TFR;
